// src/features/shipments/shipmentsData.js
const shipmentsData = [
  {
    id: 'SHP001',
    trackingNumber: 'BD123456789IN',
    receiverName: 'Rahul Sharma',
    receiverCity: 'Mumbai',
    receiverAddress: 'Flat 4B, Sector 12, Vashi, Navi Mumbai 400703',
    senderName: 'TechMart Pvt Ltd',
    senderCity: 'Delhi',
    carrier: 'BlueDart',
    weight: '2.5 kg',
    status: 'delivered',
    priority: 'standard',
    createdAt: '2026-05-28',
    estimatedDelivery: '2026-06-02',
    deliveredAt: '2026-06-01',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-05-28T10:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-05-29T09:30:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-05-30T14:00:00', note: 'Package at Delhi hub', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-06-01T08:00:00', note: 'With delivery agent', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '2026-06-01T14:30:00', note: 'Delivered to receiver', completed: true },
    ],
  },
  {
    id: 'SHP002',
    trackingNumber: 'DT987654321IN',
    receiverName: 'Priya Patel',
    receiverCity: 'Ahmedabad',
    receiverAddress: '23, Navrangpura, Ahmedabad 380009',
    senderName: 'FashionHub',
    senderCity: 'Mumbai',
    carrier: 'DTDC',
    weight: '1.2 kg',
    status: 'delivered',
    priority: 'express',
    createdAt: '2026-05-30',
    estimatedDelivery: '2026-06-03',
    deliveredAt: '2026-06-02',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-05-30T08:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-05-31T10:00:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-01T06:00:00', note: 'Package in transit via Surat', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-06-02T09:00:00', note: 'With delivery agent', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '2026-06-02T13:00:00', note: 'Delivered successfully', completed: true },
    ],
  },
  {
    id: 'SHP003',
    trackingNumber: 'DL456789123IN',
    receiverName: 'Arjun Mehta',
    receiverCity: 'Bengaluru',
    receiverAddress: '12, Koramangala 4th Block, Bengaluru 560034',
    senderName: 'ElectroZone',
    senderCity: 'Hyderabad',
    carrier: 'Delhivery',
    weight: '4.8 kg',
    status: 'in_transit',
    priority: 'standard',
    createdAt: '2026-06-05',
    estimatedDelivery: '2026-06-10',
    deliveredAt: null,
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-05T11:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-06T09:00:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-07T07:00:00', note: 'Package at Hyderabad sorting hub', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '', note: '', completed: false },
      { status: 'delivered', label: 'Delivered', timestamp: '', note: '', completed: false },
    ],
  },
  {
    id: 'SHP004',
    trackingNumber: 'EK321654987IN',
    receiverName: 'Sunita Reddy',
    receiverCity: 'Hyderabad',
    receiverAddress: 'Plot 45, Jubilee Hills, Hyderabad 500033',
    senderName: 'BookWorld',
    senderCity: 'Chennai',
    carrier: 'Ekart',
    weight: '0.8 kg',
    status: 'delivered',
    priority: 'standard',
    createdAt: '2026-05-25',
    estimatedDelivery: '2026-05-30',
    deliveredAt: '2026-05-29',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-05-25T09:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-05-26T11:00:00', note: 'Package collected', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-05-27T08:00:00', note: 'Package at Chennai hub', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-05-29T09:00:00', note: 'With delivery agent', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '2026-05-29T16:00:00', note: 'Package delivered', completed: true },
    ],
  },
  {
    id: 'SHP005',
    trackingNumber: 'FX654321789IN',
    receiverName: 'Vikram Singh',
    receiverCity: 'Delhi',
    receiverAddress: 'B-12, Connaught Place, New Delhi 110001',
    senderName: 'GlobalTech',
    senderCity: 'Mumbai',
    carrier: 'FedEx',
    weight: '6.2 kg',
    status: 'out_for_delivery',
    priority: 'overnight',
    createdAt: '2026-06-11',
    estimatedDelivery: '2026-06-13',
    deliveredAt: null,
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-11T06:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-11T14:00:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-12T02:00:00', note: 'Overnight flight to Delhi', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-06-13T08:30:00', note: 'With delivery agent in Delhi', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '', note: '', completed: false },
    ],
  },
  {
    id: 'SHP006',
    trackingNumber: 'SF789123456IN',
    receiverName: 'Ananya Iyer',
    receiverCity: 'Chennai',
    receiverAddress: '78, Anna Nagar, Chennai 600040',
    senderName: 'HomeDecor Co',
    senderCity: 'Bengaluru',
    carrier: 'Shadowfax',
    weight: '3.0 kg',
    status: 'delivered',
    priority: 'express',
    createdAt: '2026-06-01',
    estimatedDelivery: '2026-06-04',
    deliveredAt: '2026-06-03',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-01T10:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-01T18:00:00', note: 'Package collected', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-02T07:00:00', note: 'Package en route to Chennai', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-06-03T09:00:00', note: 'Out with delivery agent', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '2026-06-03T12:00:00', note: 'Delivered to receiver', completed: true },
    ],
  },
  {
    id: 'SHP007',
    trackingNumber: 'BD234567890IN',
    receiverName: 'Rohit Gupta',
    receiverCity: 'Pune',
    receiverAddress: '5, Baner Road, Pune 411045',
    senderName: 'SportZone',
    senderCity: 'Delhi',
    carrier: 'BlueDart',
    weight: '5.5 kg',
    status: 'in_transit',
    priority: 'standard',
    createdAt: '2026-06-08',
    estimatedDelivery: '2026-06-14',
    deliveredAt: null,
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-08T09:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-09T10:00:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-10T05:00:00', note: 'Package at Delhi-Pune route', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '', note: '', completed: false },
      { status: 'delivered', label: 'Delivered', timestamp: '', note: '', completed: false },
    ],
  },
  {
    id: 'SHP008',
    trackingNumber: 'DT112233445IN',
    receiverName: 'Kavitha Nair',
    receiverCity: 'Kolkata',
    receiverAddress: '34, Park Street, Kolkata 700016',
    senderName: 'MedSupply India',
    senderCity: 'Mumbai',
    carrier: 'DTDC',
    weight: '0.5 kg',
    status: 'delivered',
    priority: 'overnight',
    createdAt: '2026-06-09',
    estimatedDelivery: '2026-06-11',
    deliveredAt: '2026-06-10',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-09T07:00:00', note: 'Urgent medical shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-09T12:00:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-09T22:00:00', note: 'Overnight dispatch to Kolkata', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-06-10T09:00:00', note: 'With delivery agent', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '2026-06-10T11:30:00', note: 'Delivered successfully', completed: true },
    ],
  },
  {
    id: 'SHP009',
    trackingNumber: 'DL556677889IN',
    receiverName: 'Deepak Verma',
    receiverCity: 'Jaipur',
    receiverAddress: '88, Malviya Nagar, Jaipur 302017',
    senderName: 'CraftBasket',
    senderCity: 'Ahmedabad',
    carrier: 'Delhivery',
    weight: '2.1 kg',
    status: 'failed',
    priority: 'standard',
    createdAt: '2026-06-04',
    estimatedDelivery: '2026-06-08',
    deliveredAt: null,
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-04T10:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-05T09:30:00', note: 'Package collected', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-06T06:00:00', note: 'Package at Ahmedabad hub', completed: true },
      { status: 'failed', label: 'Delivery Failed', timestamp: '2026-06-08T14:00:00', note: 'Receiver not available, address incorrect', completed: true },
    ],
  },
  {
    id: 'SHP010',
    trackingNumber: 'EK998877665IN',
    receiverName: 'Megha Joshi',
    receiverCity: 'Mumbai',
    receiverAddress: '201, Linking Road, Bandra West, Mumbai 400050',
    senderName: 'GadgetWorld',
    senderCity: 'Bengaluru',
    carrier: 'Ekart',
    weight: '3.7 kg',
    status: 'delivered',
    priority: 'express',
    createdAt: '2026-06-02',
    estimatedDelivery: '2026-06-05',
    deliveredAt: '2026-06-04',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-02T09:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-02T16:00:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-03T08:00:00', note: 'Package at Bengaluru airport', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-06-04T09:30:00', note: 'Out with delivery agent', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '2026-06-04T15:00:00', note: 'Delivered to receiver', completed: true },
    ],
  },
  {
    id: 'SHP011',
    trackingNumber: 'FX741852963IN',
    receiverName: 'Anil Kumar',
    receiverCity: 'Hyderabad',
    receiverAddress: '9, Banjara Hills Road No 12, Hyderabad 500034',
    senderName: 'LuxuryGoods Inc',
    senderCity: 'Delhi',
    carrier: 'FedEx',
    weight: '1.8 kg',
    status: 'delivered',
    priority: 'overnight',
    createdAt: '2026-06-06',
    estimatedDelivery: '2026-06-08',
    deliveredAt: '2026-06-07',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-06T08:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-06T14:00:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-07T01:00:00', note: 'Overnight flight to Hyderabad', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-06-07T09:00:00', note: 'With delivery agent', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '2026-06-07T12:30:00', note: 'Delivered to receiver', completed: true },
    ],
  },
  {
    id: 'SHP012',
    trackingNumber: 'SF963741852IN',
    receiverName: 'Pooja Sharma',
    receiverCity: 'Pune',
    receiverAddress: 'A-7, Aundh, Pune 411007',
    senderName: 'FreshFarm Co',
    senderCity: 'Nashik',
    carrier: 'Shadowfax',
    weight: '4.0 kg',
    status: 'returned',
    priority: 'express',
    createdAt: '2026-06-03',
    estimatedDelivery: '2026-06-06',
    deliveredAt: null,
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-03T09:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-03T14:00:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-04T07:00:00', note: 'Package in transit', completed: true },
      { status: 'failed', label: 'Delivery Failed', timestamp: '2026-06-06T11:00:00', note: 'Customer refused delivery', completed: true },
      { status: 'returned', label: 'Returned to Sender', timestamp: '2026-06-08T15:00:00', note: 'Package returned to origin', completed: true },
    ],
  },
  {
    id: 'SHP013',
    trackingNumber: 'BD345678901IN',
    receiverName: 'Suresh Patel',
    receiverCity: 'Ahmedabad',
    receiverAddress: 'C-45, Satellite Road, Ahmedabad 380015',
    senderName: 'AutoParts Hub',
    senderCity: 'Pune',
    carrier: 'BlueDart',
    weight: '8.3 kg',
    status: 'in_transit',
    priority: 'standard',
    createdAt: '2026-06-10',
    estimatedDelivery: '2026-06-15',
    deliveredAt: null,
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-10T10:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-11T09:00:00', note: 'Package collected', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-12T04:00:00', note: 'Package at Pune hub', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '', note: '', completed: false },
      { status: 'delivered', label: 'Delivered', timestamp: '', note: '', completed: false },
    ],
  },
  {
    id: 'SHP014',
    trackingNumber: 'DT667788990IN',
    receiverName: 'Nisha Kulkarni',
    receiverCity: 'Navi Mumbai',
    receiverAddress: '303, Sector 15, Vashi, Navi Mumbai 400703',
    senderName: 'KidsZone Store',
    senderCity: 'Kolkata',
    carrier: 'DTDC',
    weight: '1.5 kg',
    status: 'delivered',
    priority: 'standard',
    createdAt: '2026-05-20',
    estimatedDelivery: '2026-05-26',
    deliveredAt: '2026-05-25',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-05-20T10:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-05-21T11:00:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-05-22T06:00:00', note: 'Package in transit', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-05-25T08:30:00', note: 'With delivery agent', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '2026-05-25T14:00:00', note: 'Delivered to receiver', completed: true },
    ],
  },
  {
    id: 'SHP015',
    trackingNumber: 'DL112244336IN',
    receiverName: 'Rajesh Nair',
    receiverCity: 'Chennai',
    receiverAddress: '56, T Nagar, Chennai 600017',
    senderName: 'PrintMasters',
    senderCity: 'Hyderabad',
    carrier: 'Delhivery',
    weight: '2.9 kg',
    status: 'pending',
    priority: 'standard',
    createdAt: '2026-06-13',
    estimatedDelivery: '2026-06-18',
    deliveredAt: null,
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-13T09:00:00', note: 'Shipment booked, awaiting pickup', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '', note: '', completed: false },
      { status: 'in_transit', label: 'In Transit', timestamp: '', note: '', completed: false },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '', note: '', completed: false },
      { status: 'delivered', label: 'Delivered', timestamp: '', note: '', completed: false },
    ],
  },
  {
    id: 'SHP016',
    trackingNumber: 'EK445566778IN',
    receiverName: 'Shreya Bhatt',
    receiverCity: 'Bengaluru',
    receiverAddress: '18, Indiranagar 100ft Road, Bengaluru 560038',
    senderName: 'HealthPlus',
    senderCity: 'Mumbai',
    carrier: 'Ekart',
    weight: '0.6 kg',
    status: 'delivered',
    priority: 'express',
    createdAt: '2026-06-07',
    estimatedDelivery: '2026-06-10',
    deliveredAt: '2026-06-09',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-07T10:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-07T17:00:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-08T06:00:00', note: 'Package in transit', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-06-09T09:00:00', note: 'With delivery agent', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '2026-06-09T13:30:00', note: 'Delivered to receiver', completed: true },
    ],
  },
  {
    id: 'SHP017',
    trackingNumber: 'FX852963741IN',
    receiverName: 'Amit Tiwari',
    receiverCity: 'Delhi',
    receiverAddress: '44, Lajpat Nagar II, New Delhi 110024',
    senderName: 'Office Essentials',
    senderCity: 'Jaipur',
    carrier: 'FedEx',
    weight: '7.1 kg',
    status: 'out_for_delivery',
    priority: 'express',
    createdAt: '2026-06-11',
    estimatedDelivery: '2026-06-13',
    deliveredAt: null,
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-11T08:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-11T15:00:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-12T08:00:00', note: 'Package at Jaipur hub', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-06-13T09:30:00', note: 'With delivery agent in Delhi', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '', note: '', completed: false },
    ],
  },
  {
    id: 'SHP018',
    trackingNumber: 'SF147258369IN',
    receiverName: 'Prathima Rao',
    receiverCity: 'Hyderabad',
    receiverAddress: '67, Madhapur, Hyderabad 500081',
    senderName: 'AgroFresh',
    senderCity: 'Bengaluru',
    carrier: 'Shadowfax',
    weight: '3.5 kg',
    status: 'delivered',
    priority: 'standard',
    createdAt: '2026-05-22',
    estimatedDelivery: '2026-05-27',
    deliveredAt: '2026-05-26',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-05-22T10:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-05-23T09:30:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-05-24T07:00:00', note: 'Package at Bengaluru hub', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-05-26T08:30:00', note: 'With delivery agent', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '2026-05-26T15:00:00', note: 'Delivered to receiver', completed: true },
    ],
  },
  {
    id: 'SHP019',
    trackingNumber: 'BD456789012IN',
    receiverName: 'Kiran Desai',
    receiverCity: 'Mumbai',
    receiverAddress: '11, Worli Sea Face, Mumbai 400018',
    senderName: 'ArtisanCraft',
    senderCity: 'Kolkata',
    carrier: 'BlueDart',
    weight: '2.2 kg',
    status: 'delivered',
    priority: 'standard',
    createdAt: '2026-06-03',
    estimatedDelivery: '2026-06-08',
    deliveredAt: '2026-06-07',
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-03T10:00:00', note: 'Shipment booked', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '2026-06-04T09:00:00', note: 'Package collected from sender', completed: true },
      { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-05T07:00:00', note: 'Package at Kolkata hub', completed: true },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '2026-06-07T08:30:00', note: 'With delivery agent', completed: true },
      { status: 'delivered', label: 'Delivered', timestamp: '2026-06-07T13:00:00', note: 'Delivered to receiver', completed: true },
    ],
  },
  {
    id: 'SHP020',
    trackingNumber: 'DT778899001IN',
    receiverName: 'Farhan Sheikh',
    receiverCity: 'Pune',
    receiverAddress: '22, Kothrud, Pune 411038',
    senderName: 'TrendWear',
    senderCity: 'Delhi',
    carrier: 'DTDC',
    weight: '1.9 kg',
    status: 'pending',
    priority: 'express',
    createdAt: '2026-06-13',
    estimatedDelivery: '2026-06-16',
    deliveredAt: null,
    timeline: [
      { status: 'pending', label: 'Order Placed', timestamp: '2026-06-13T11:00:00', note: 'Shipment booked, awaiting pickup', completed: true },
      { status: 'picked_up', label: 'Picked Up', timestamp: '', note: '', completed: false },
      { status: 'in_transit', label: 'In Transit', timestamp: '', note: '', completed: false },
      { status: 'out_for_delivery', label: 'Out for Delivery', timestamp: '', note: '', completed: false },
      { status: 'delivered', label: 'Delivered', timestamp: '', note: '', completed: false },
    ],
  },
]

export default shipmentsData
